## 回家作業：檔案存取

In [10]:
import  json, ssl, urllib.request
url = 'http://opendataap2.penghu.gov.tw/resource/files/2021-03-31/42c8286112bff4bc191ed998df3abaf1.json'
context = ssl._create_unverified_context()
with urllib.request.urlopen(url,context=context) as jsondata:    
     data = json.loads(jsondata.read())
titleList=[*data[0].keys()][0:3] ##取得前3各columns
#print(titleList)
for  jsonData in data:    
  for title in titleList:
      print(jsonData[title],end=' ')
  #print(jsonData)  
  print("\n")

農產推廣--農產推廣 辦理澎湖縣各界慶祝105年農民節大會活動經費 澎湖縣農會 

社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉外垵社區發展協會 

社區發展--社區發展 105年度垃圾分類暨資源回收宣導 澎湖縣西嶼鄉大池社區發展協會 

社區發展--社區發展 105年年關交通安全宣導活動暨鄰長聯誼餐敘 澎湖縣西嶼鄉橫礁社區發展協會 

社區發展--社區發展 年節防詐騙及安全宣導計畫 澎湖縣西嶼鄉二崁社區發展協會 

社區發展--社區發展 年關慢性病防治宣導暨社區志工及老人聯誼餐敘 澎湖縣西嶼鄉橫礁社區發展協會 

社區發展--社區發展 105年防詐騙住宅防竊宣導活動 澎湖縣西嶼鄉赤馬社區發展協會 

社區發展--社區發展 105年垃圾分類暨資源回收宣導 澎湖縣西嶼鄉小門社區發展協會 

社區發展--社區發展 內垵擊鼓表演暨村鄰長聯誼活動 澎湖縣西嶼鄉內垵社區發展協會 

社區發展--社區發展 歡慶元宵聯歡晚會 澎湖縣西嶼鄉小門社區發展協會 

社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉大池社區發展協會 

社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉赤馬社區發展協會 

社區發展--社區發展 105年池府王爺平安繞境活動 澎湖縣西嶼鄉內垵社區發展協會 

社區發展--社區發展 105年平安燒境祈福活動 澎湖縣西嶼鄉赤馬社區發展協會 

社區發展--社區發展 105年老人關懷據點-點心品嚐活動 澎湖縣西嶼鄉內垵社區發展協會 

社區發展--社區發展 2016丙申年金猴獻瑞慶元宵民俗活動 澎湖縣西嶼鄉外垵社區發展協會 

社區發展--社區發展 105年歡慶元宵猜燈謎晚會活動 澎湖縣西嶼鄉內垵社區發展協會 

社區發展--社區發展 105年度聯合社區計畫 澎湖縣西嶼鄉竹灣社區發展協會 

社區發展--社區發展 召開第六屆第一次會員大會暨春節聯誼活動費 澎湖視障協進會 

社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉橫礁社區發展協會 

社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉竹灣社區發展協會 

社區發展--社區發展 福德宮鎮符遶境祈福活動 澎湖縣西嶼鄉池西社區發展協會 

社區發展--社區發展 晨泳協會辦理晨泳安全講習活動 澎湖縣西嶼晨泳協會 

社區發展--社區發展 辦理105年戒煙宣導暨歌唱聯誼活動 澎湖縣內

## 陣列指定位置-給予一個整數
+ 關於指定位置  [row,column]
+ 假設給予一個整數為 N
 + 如果是給固定的 N，那就代表 row 或 column 等於 N。
 + 如果是 N：，那就代表 row 或 column 大於等於 N 的區域。
 + 如果是：N，那就代表 row 或 column 小於 N 的區域。 
 + 如果是：，那就代表 row 或 column 是任意欄位。

In [11]:
import numpy as np
a = np.array([[1,2,3],[3,6,9],[2,4,6]])
print("---1--")
print(a)
print("---2--")
print(a[0])
print("---3--")
print(a[1,2])

---1--
[[1 2 3]
 [3 6 9]
 [2 4 6]]
---2--
[1 2 3]
---3--
9


In [15]:
import numpy as np
a = np.array([[1, 2, 3], 
              [3, 6, 9],
              [2, 4, 6]])
print(a[1, 1:3])
print("---------------")
print(a[:,1])
print("---------------")
a[1, 2] = 7
print(a)
print("---------------")
a[:, 0] = [0, 9, 8]
print(a)
print("---------------")

[6 9]
---------------
[2 6 4]
---------------
[[1 2 3]
 [3 6 7]
 [2 4 6]]
---------------
[[0 2 3]
 [9 6 7]
 [8 4 6]]
---------------


In [16]:
import numpy as np
a = np.array([[0,1,2,3,4,5],
       [10,11,12,13,14,15],
       [20,21,22,23,24,25],
       [30,31,32,33,34,35],
       [40,41,42,43,44,45],
       [50,51,52,53,54,55],
])
print("---1--")
print(a[0,3:5])
print("---2--")
print(a[4:,4:])
print("---3--")
print(a[:3,:3])
print("---4--")
print(a[:,2])


---1--
[3 4]
---2--
[[44 45]
 [54 55]]
---3--
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
---4--
[ 2 12 22 32 42 52]


## 陣列指定位置 - tuple 或 list
+ 如果是 tuple 方式，代表位置第一個 tuple 的每一個值為 row 的位置，第二個 tuple 的每一個值為 column 的位置。
+ 如果是 list 方式，代表 row 或 column 要選取 index 為 list 上的數值的資料。

In [17]:
import numpy as np
a = np.array([
       [0,1, 2, 3,4,5],
       [10,11,12,13,14,15],
       [20,21,22,23,24,25],
       [30,31,32,33,34,35],
       [40,41,42,43,44,45],
       [50,51,52,53,54,55],
       ])
print("---1--")
print(a[(0,1,2,3,4),(1,2,3,4,5)])
print("---2--")
print(a[3:,[0, 2, 5]])


---1--
[ 1 12 23 34 45]
---2--
[[30 32 35]
 [40 42 45]
 [50 52 55]]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置

### 操作範例：reshape

In [23]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print("==================")
b = a.reshape(3,2)
print(b)
print("==================")
print(b.shape)
print("=======a===========")
print(a)
a[0,1] = 100
print("==================")
print(b) # 會改變
print("==================")
print(b.shape)
print("==================")
print(a.shape)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
=======a===========
[[1 2 3]
 [4 5 6]]
[[  1 100]
 [  3   4]
 [  5   6]]
(3, 2)
(2, 3)


### resize

In [27]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print("==========================")
b = np.resize(a,(3,2))#會複製一份資料來源
print(b)
print(b.shape)
print("==========================")
a[0,1] = 100
print(b)#不會改變
print(b.shape)
print(a.shape)
b = np.resize(a,(10,10))#resize 大於原本size
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
(2, 3)
[[  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]]


### transpose

In [29]:
import numpy as np
newArray = np.arange(10).reshape(2,5)
print("================")
print(newArray)
print("================")
print(newArray.transpose())
print("================")
print(newArray) ## 原始陣列部會改變
print("================")
tArray = newArray.T
print(tArray)
print("======TT==========")
tArray = tArray.T
print(tArray)
print("================")
tArray[1] = 10
print("================")
print(tArray)
print("================")
print(newArray)#影響原始資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
======TT==========
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [10 10 10 10 10]]
[[ 0  1  2  3  4]
 [10 10 10 10 10]]


## 數值計算
+ 數值計算函數內放入參與計算的兩個陣列。
+ 進行計算的陣列第一維數量必須是相同。
+ add( ) 方法代表「加」，也可以使用「+」。
+ subtract( ) 方法代表「減」，也可以使用「-」。
+ multiply( )方法代表「乘」，也可以使用「*」。
+ divide( ) 方法代表「除」，也可以使用「/」。

In [33]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,10,10]])
c = np.add(a,b)
print(c)
d = np.subtract(a,b)
print(d)

a: (3, 3)
b: (1, 3)
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


In [34]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])#(3,3)
b = np.array([10,10,10])#(3)
c=a+b
print(c)
print( )
d= a-b
print(d)
print( )

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]



## 數值計算
+ np.power(a,n) 代表 a 陣列的 n 次方。
+ a 陣列的 n 次方也可以使用 a**n 方式表示。
+ N 可以是陣列，但兩陣列第一維數量必須是相同。
+ np. Reciprocal( ) 代表倒數的計算，倒數是指a*b=1，輸入 a 後求 b。 1/4的倒數是4

In [35]:
import numpy as np
a = np.array([4,5,6])
print(a)
b = np.power(a,2)
print(b)
c = np.array([1,2,3])
d = np.power(a,c)
print(d)
h = a**c
print(h)

[4 5 6]
[16 25 36]
[  4  25 216]
[  4  25 216]


### reciprocal求倒數

In [36]:
import numpy as np
a = np.array([0.25, 1.33, 1, -0.1, 100])
print(a)
print( )
b=np.reciprocal(a) # 求倒數
print(b)
print( )

[  0.25   1.33   1.    -0.1  100.  ]

[  4.          0.7518797   1.        -10.          0.01     ]



## 除法計算與小數處理
+ np.mod( ) 方法內需加入兩個資料，例如 a 與 b，代表 a除以 b 的餘數。
+ np.remainder( ) 方法等同 np.mod( )。
+ np.around( ) 方法代表您要將浮點數資料整數位取四捨五入到第幾個位置，小數位取最接近的偶數，這個方法內需要兩個參數：
+ array：進行分析的陣列。
+ decimals小數位數：
  + 預設為 0。
  + 如果為正數，代表小數位數有幾個位子。
  + 如果為負數，代表小數點左邊的正整數將依序四捨五入進位。
+ np.floor( ) 方法代表回傳不大於輸入參數的最大整數。
+ np.ceil( ) 方法代表回傳大於輸入參數的最小整數。
+ 對於恰好介於四舍五入後的十進製值之間的值，NumPy會四舍五入為最接近的偶數值。因此，將1.5和2.5舍入為2.0，將-0.5和0.5舍入為0.0 

### 餘數Mod

In [37]:
import numpy as np
a = np.array([10,20,30])
b = np.array([3,5,7])
print(a)
print( )
c=np.mod(a,b)
print(c)
print( )
d=np.remainder(a,b)
print(d)
print( )

[10 20 30]

[1 0 2]

[1 0 2]



### around

In [43]:
import numpy as np
print(np.around([1.5, 2.5], decimals=0))
print(np.around([1.51, 2.51], decimals=0))
print(np.around([-0.5, 0.5,0.567], decimals=0))

[2. 2.]
[2. 3.]
[-0.  0.  1.]


In [59]:
import numpy as np
a = np.array([1.0,5,5.45,125,165, 0.56, 25.532])
#print(a)
print()
b=np.around(a)
#print(b)
print(np.around(a, decimals = 1) )
print(np.around(a, decimals = -1))# 如果為負數，代表小數點左邊的正整數將依序四捨五入進位。
print(np.around(a, decimals = -2))


[  1.    5.    5.4 125.  165.    0.6  25.5]
[  0.   0.  10. 120. 160.   0.  30.]
[  0.   0.   0. 100. 200.   0.   0.]


In [62]:
import numpy as np
a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
print(a)
print( )
b=np.floor(a)
print(b)
print( )
c=np.ceil(a)
print(c)
print( )

[-1.7  1.5 -0.2  0.6 10. ]

[-2.  1. -1.  0. 10.]

[-1.  2. -0.  1. 10.]



## 總和最大與最小
+ np.sum( ) 代表某一個陣列內容的總和，也可以指定這個陣列的哪一軸 (axis) 內容總和。
+ np.min( ) 代表某一個陣列內容的最小值，也可以指定這個陣列的哪一軸 (axis) 內容的最小值。
+ np.max( ) 代表某一個陣列內容的最大值，也可以指定這個陣列的哪一軸 (axis) 內容的最大值。
+ amin 與 min 是相同功能的方法。
+ amax 與 max 是相同功能的方法。

### 總和sum()

In [63]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
print("---------------")
b=np.sum(a)# 無選軸 每個元素相加
print(b)
print("---------------")
b=np.sum(a,axis=0) #拿row的陣列相加
print(b)
print("---------------")
b=np.sum(a,axis=1)#每個陣列的colum相加
print(b)
print("---------------")

[[ 0 30 45]
 [60 75 90]]
---------------
300
---------------
[ 60 105 135]
---------------
[ 75 225]
---------------


### max() min()

In [64]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
print("---------------")
b=np.max(a)
print(b)
print("---------------")
b=np.max(a,axis=0)#拿每個row的陣列找出最大值
print(b)
print("---------------")
b=np.max(a,axis=1)#拿每個colum內容比較找出最大值
print(b)
print("---------------")

[[ 0 30 45]
 [60 75 90]]
---------------
90
---------------
[60 75 90]
---------------
[45 90]
---------------


## 中位數與平均
+ median( ) 方法可取出陣列或陣列中指定的軸之中位數。
+ 把所有值高低排序後找出正中間的一個作爲中位數。如果資料數量為偶數，則中位數取最中間的兩個數值的平均數。
+ 參數：
  + array：陣列
  + axis：軸
+ mean( ) 方法可取出陣列或陣列中指定的軸之平均數。
+ 平均值就是把陣列或指定軸的所有資料除以數量後的數值。
+ 參數：
    + array：陣列 
    + axis：軸
+ average( ) 方法與 mean( ) 方法相似，但可以加入權重進行計算。
+ 計算公式為 ((資料*權重)相加)/(權重相加)
+ 參數：
  + array：陣列
  + axis：軸
  + weights：權重，若沒有則設定為 1
  + returned：若設定為 true，代表返回計算結果跟權重相加總合兩筆資料，若沒有設定或設定  false 則只有計算結果 
+ 沒有指定權重時與一般平均值相同。
+ 加權平均值是由每個資料乘以權重以反映加上重要性因素後產生的平均值。
+ average( ) 使用時若沒有指定軸，則陣列將被平坦化。
+ 假設有個陣列資料為 [1,2,3,4]，相應的權重 [40,30,20,10]，加權平均數是這樣：
    (1x40+2x30+3x20+4x10)/(40+30+20+10)
  

In [65]:
import numpy as np
a = np.array([[0, 30,45],[60,75,90]])
print(a)
print()
b=np.median(a)# 6/2 = 3 取出 3與4編號的數字45與60 (45 + 60) /2
print(b)
print()
b=np.median(a, axis = 0)
print(b)
print()
b=np.median(a, axis = 1)
print(b)

[[ 0 30 45]
 [60 75 90]]

52.5

[30.  52.5 67.5]

[30. 75.]


### 平均值

In [66]:
import numpy as np
a = np.array([[0, 30,45],[60,75,90]])
print(a)
print( )
b=np.mean(a)#平均值
print(b)
print( )
b=np.mean(a, axis = 0)
print(b)
print( )
b=np.mean(a, axis = 1)
print(b)
print( )

[[ 0 30 45]
 [60 75 90]]

50.0

[30.  52.5 67.5]

[25. 75.]



## average()

In [68]:
import numpy as np
a = np.array([1,2,3,4])
b=np.average(a)
print(b)
print( )
wts = np.array([4,3,2,1])
b=np.average(a,weights = wts)
print(b)
print( )
b=np.average([1,2,3,4],weights = [4,3,2,1], returned = True)
#(1*4+2*3+3*2+4*1)/(4+3+2+1)  
# 20/10  = 2
#4+3+2+1 = 10
ans,wgsum = b
print(b)
print(ans,wgsum)

2.5

2.0

(2.0, 10.0)
2.0 10.0


## Numpy增減與統計

## 陣列附加資料
+ 這個方法動作將在陣列末端附加資料。
+ 若沒有指定軸 (維度) 則代表於陣列增加資料，陣列變成一維。
+ 維度必須相同
+ append 需要以下參數：
  + arr：想要附加資料的陣列。
  + values：想要附加於 arr 這個陣列後面的資料，資料的形狀必須與 arr 陣列相同。
  + axis：可以指定附加於哪一個軸 (維度) .

In [69]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)            
b = np.append(a,[7,8,9])
print(b) 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]


In [72]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)       
print("===================")  
b = np.append(a,[[7,8,9]],axis=0)
print(b) 
print("===================")  
b = np.append(a,[[7,8,9],[10,11,12]],axis=0)
print(b) 

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [74]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
d = np.append(a,[[7,10],[8,20]],axis=1)
print(d)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3  7 10]
 [ 4  5  6  8 20]]


## 陣列插入資料
+ 這個動作方法會依照指定的軸 (維度) 與指定的索引的陣列插入資料。
+ 如果沒有提到軸 (維度)，陣列將會變成一維。
+ insert( ) 函數需要以下參數：
  + arr：欲插入的陣列。
  + index：插入位置的索引值編號。
  + values：要插入的內容。
  + axis：指定的軸 (維度)，如果沒有給這參數，則會變成一維。

In [75]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
b = np.insert(a,3,[11,12])# 因為沒指定軸展開成為一維
print(b)

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]


In [78]:
import numpy as np
a = np.array([[1,2],
              [3,4],
              [5,6]])
print(a)
print()
c = np.insert(a,1,[11],axis=0)
print(c)
print()
c = np.insert(a,1,[11,18],axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]

[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]

[[ 1  2]
 [11 18]
 [ 3  4]
 [ 5  6]]


In [79]:
import numpy as np
a = np.array([[1,2],
              [3,4],
              [5,6]])
print(a)
print( )
d=np.insert(a,1,11,axis = 1)
print(d)
d=np.insert(a,1,[11,18,17],axis = 1)
print( )
print(d)
d=np.insert(a,1,[11,18],axis = 1) ## 錯誤 因為 欄的長度是3 插入數資料長度為2
print( )
print(d)


[[1 2]
 [3 4]
 [5 6]]

[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]

[[ 1 11  2]
 [ 3 18  4]
 [ 5 17  6]]


ValueError: could not broadcast input array from shape (2,1) into shape (3,1)